name: dicegame
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rename_app: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.3
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/Dices/Dice1.png
    - assets/images/Dices/Dice2.png
    - assets/images/Dices/Dice3.png
    - assets/images/Dices/Dice4.png
    - assets/images/Dices/Dice5.png
    - assets/images/Dices/Dice6.png
  
  fonts:
    - family: KingdomComeText
      fonts:
        - asset: assets/fonts/1529 Champ Fleury W01 Regular.ttf
    - family: KingdomComeTitle
      fonts:
        - asset: assets/fonts/Maximilian.ttf

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/appIcon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

flutter_app_name:
  name: "Dice Game"